// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCQcGXm7iqF9kzjOCYIMfzzwoyRtO04jE',
    appId: '1:486612088522:web:9f93b3b13fa005f82be633',
    messagingSenderId: '486612088522',
    projectId: 'ajiapp-d436f',
    authDomain: 'ajiapp-d436f.firebaseapp.com',
    storageBucket: 'ajiapp-d436f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvMxcdhWsTPSJwPx01OZn9l7RX1jF6sWA',
    appId: '1:486612088522:android:1149ed31cae774742be633',
    messagingSenderId: '486612088522',
    projectId: 'ajiapp-d436f',
    storageBucket: 'ajiapp-d436f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPTYo_4hwCpl4zHwGAQ-yp1hZrpxC3_i8',
    appId: '1:486612088522:ios:54d3b711ee6909932be633',
    messagingSenderId: '486612088522',
    projectId: 'ajiapp-d436f',
    storageBucket: 'ajiapp-d436f.firebasestorage.app',
    iosBundleId: 'com.example.ajiapp',
  );
}
